# Generated by Django 5.2.8 on 2025-11-22 11:41

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cats', '0001_initial'),
        ('missions', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cat',
            name='active_mission',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_cat', to='missions.mission'),
        ),
    ]
